### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by chatelao** [microsoft/pxt-adafruit#1196]
https://github.com/microsoft/pxt-adafruit/blob/master/sim/dalboard.ts#L140

```typescript
[run] cd sim; node ../node_modules/typescript/bin/tsc
dalboard.ts:140:54 - error TS2554: Expected 1 arguments, but got 0.

140             this.builtinParts["ir"] = this.irState = new InfraredState();
                                                         ~~~~~~~~~~~~~~~~~~~

  ../built/common-sim.d.ts:752:21
    752         constructor(board: BaseBoard);
                            ~~~~~~~~~~~~~~~~
    An argument for 'board' was not provided.


Found 1 error.

INTERNAL ERROR: Error: Exit code: 2 from cd sim; node ../node_modules/typescript/bin/tsc
    at ChildProcess.<anonymous> (/home/vagrant/pxt/built/nodeutil.js:85:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
setup.sh completed
```

**Comment by adjian** [comment]
Hello, I met the same error. Do you have some solution for this issue? Can you share your solution?  Thanks!
