### ISSUE TITLE
node hidserial doesn't work

### ISSUE THREAD

**Issue by deanm1278** [Microsoft/pxt-adafruit#770]
we used to be able to do `pxt hidserial` to view debug messages. This no longer works. it shows 
```
C:\Users\deanm\Documents\dev_stuff\pxt-adafruit>pxt hidserial
Using target adafruit with build engine codal
  target: v1.1.37 C:\Users\deanm\Documents\dev_stuff\pxt-adafruit
  pxt-core: v3.18.28 C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core
INTERNAL ERROR: TypeError: hid.devices is not a function
    at getHF2Devices (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core\built\hid.js:57:23)
    at HidIO.connect (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core\built\hid.js:135:24)
    at new HidIO (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core\built\hid.js:129:14)
    at hf2ConnectAsync (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core\built\hid.js:77:29)
    at initAsync (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core\built\hid.js:95:18)
    at Object.serialAsync [as _callback] (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core\built\hid.js:30:12)
    at CommandParser.parseCommand (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core\built\commandparser.js:117:24)
    at C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core\built\pxt.js:135753:18
    at tryCatcher (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._fulfillPromises (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\bluebird\js\release\promise.js:668:14)
    at Promise._settlePromises (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\bluebird\js\release\promise.js:694:18)
    at Async._drainQueue (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\bluebird\js\release\async.js:17:14)
```

**Comment by pelikhan** [comment]
Fixed.
